### ISSUE TITLE
index(index: Int, f: (Assert<T>) and all(f: Assert<T>.() -> Unit) should have similar signatures for the lamdas

### ISSUE THREAD

**Issue by JotBePunkt** [willowtreeapps/assertk#159]
Currenly the lamdas in `all` and `index` have different signatures leading to strange exceptions:

```
class Event(val date:LocalDate = LocalDate.now)

fun test() {
    val events = setOf(Event(), Event())

    assert(events).all {
       hasSize(2)
       index(0) {
          prop(Event::date)
             .isEqualTo(LocalDate.of(2018, Month.December, 20))
       }
   }
}
```   
leads to the following exception as the method `prop` is not called in the implicit `it` if the `index` lamda but on `this` of the `all` extension lamda.
```
java.lang.IllegalArgumentException: object is not an instance of declaring class

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:71)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:87)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
	at kotlin.jvm.internal.CallableReference.call(CallableReference.java:138)
	at assertk.assertions.AnyJVMKt$prop$1.invoke(any.kt:74)
	at assertk.assertions.AnyKt.prop(any.kt:143)
	at assertk.assertions.AnyJVMKt.prop(any.kt:74)
       [...]
```

My suggestion would be to make both lamdas an extension because thats the most intuitive.

**Comment by JotBePunkt** [comment]
Just seeing that in the latest source code that method is deprecated... Thats also a good solution...
