### ISSUE TITLE
OpenTest4j issue in JUnit 4-driven tests

### ISSUE THREAD

**Issue by realdadfish** [willowtreeapps/assertk#172]
On request in #70 OpenTest4j support was added, but that doesn't seem to exist in the classpath during test execution in IntelliJ:

```
java.lang.AssertionError: java.lang.NoClassDefFoundError: org/opentest4j/AssertionFailedError

	at my.package.MyTest.shouldVerifySomething(MyTest.kt:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:600)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NoClassDefFoundError: org/opentest4j/AssertionFailedError
	at assertk.FailureKt.fail(failure.kt:98)
	at assertk.assertions.support.SupportKt.expected(support.kt:72)
	at assertk.assertions.support.SupportKt.expected$default(support.kt:69)
	at assertk.assertions.AnyKt$isInstanceOf$1.invoke(any.kt:209)
	at assertk.Assert.transform(assert.kt:26)
	at assertk.assertions.AnyKt.isInstanceOf(any.kt:204)
	... 26 more
Caused by: java.lang.ClassNotFoundException: org.opentest4j.AssertionFailedError
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:163)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:118)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$findClass$0(SandboxClassLoader.java:111)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:50)
	at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:110)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more
```
When running the test outside of the IDE, e.g. through Gradle, the dependency is apparently there and the assertion is properly hit.

I'm using assertk-jvm 0.13.

This might be related to https://github.com/joel-costigliola/assertj-core/issues/1072

**Comment by realdadfish** [comment]
This is btw unrelated to Robolectric, as the regular class loader won't find opentest4j on the classpath either:

```
java.lang.AssertionError: java.lang.NoClassDefFoundError: org/opentest4j/AssertionFailedError

	at my.package.Foo.testFoo(Foo.kt:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NoClassDefFoundError: org/opentest4j/AssertionFailedError
	at assertk.FailureKt.fail(failure.kt:98)
	at assertk.assertions.support.SupportKt.expected(support.kt:72)
	at assertk.assertions.support.SupportKt.fail(support.kt:54)
	at assertk.assertions.AnyKt.isEqualTo(any.kt:33)
	... 23 more
Caused by: java.lang.ClassNotFoundException: org.opentest4j.AssertionFailedError
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more

**Comment by evant** [comment]
Hm, could do what assertj is doing and only use that class if it's on the classpath, but it's explicitly pulling in the dependency so this sounds like an IDE bug. What version of intellij are you using?

**Comment by realdadfish** [comment]
Android Studio 3.3 final. 

Am 7. Februar 2019 15:57:39 MEZ schrieb Evan Tatarka <notifications@github.com>:
>Hm, could do what assertj is doing and only use that class if it's on
>the classpath, but it's explicitly pulling in the dependency so this
>sounds like an IDE bug. What version of intellij are you using?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/willowtreeapps/assertk/issues/172#issuecomment-461454898

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by evant** [comment]
Have you tried setting `Preferences | Build, Execution, Deployment | Build Tools | Gradle | Runner | Run tests using: Gradle Test Runner`? That might get it working for now.

**Comment by realdadfish** [comment]
Will try that tomorrow. Thanks for the pointer! 

Am 7. Februar 2019 16:05:41 MEZ schrieb Evan Tatarka <notifications@github.com>:
>Have you tried setting `Preferences | Build, Execution, Deployment |
>Build Tools | Gradle | Runner | Run tests using: Gradle Test Runner`?
>That might get it working for now.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/willowtreeapps/assertk/issues/172#issuecomment-461458440

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by evant** [comment]
I'd really rather this gets fixed upstream. If anyone is running into this issue, can you report:
1. Which IDE are you using (Android Studio, Intellij CE, Intellij Ultimate)
1. What version you are running
2. What OS you are on
3. What version of the IDE kotlin plugin you are using
4. If you are running tests with the built-in runner or the gradle test runner

Also, it would be helpful to test if it's still an issue on the latest version of the IDE if you are not on it. A sample project might also be helpful for reproduction.

**Comment by evant** [comment]
Let me start:

1. Intellij CE
2. 2019.1.3 Preview
3. Linux
4. v1.3.31-relese-IJ2019.1-1
5. Both

**Comment by evant** [comment]
I think I've found a work-around:

```
testCompile "org.junit.jupiter:junit-jupiter-api:5.4.2"
```

**Comment by evant** [comment]
Filed a bug https://youtrack.jetbrains.com/issue/IDEA-214533

**Comment by evant** [comment]
Curious if anyone is still experiencing this? I think it might be fixed in newer versions of intellij.

**Comment by realdadfish** [comment]
I no longer use this library in a project, so I can't currently test. I will close this issue therfore.
