### ISSUE TITLE
Expected/Actual Reported as Null?

### ISSUE THREAD

**Issue by geoffreywiseman** [willowtreeapps/assertk#180]
I don't know if it's just the tests I'm writing lately, but I'm seeing a fair number of these kinds of failures lately:

```
org.opentest4j.AssertionFailedError: expected to contain exactly:
 at index:2 
Expected :null
Actual   :null
<Click to see difference>
```

From an assertion like this:
```		
val expectedValues = arrayOf( "ONE", "TWO" )
assertThat(Option.getByCompatibleFooType(Foo.BAR)).containsExactly(*expectedValues)
```

Neither the expected or actual arrays contain null, but the assertion error doesn't actually tell me what the problem is.

**Comment by evant** [comment]
Hm, do you have a sample test that does this?

**Comment by geoffreywiseman** [comment]
Given this class:

```kotlin
package com.willowtreeapps.assertk.bug

enum class Option {
	ONE, TWO, THREE, FOUR, FIVE;

	companion object {
		fun getCompatibleOptions(): List<String> {
			return listOf( ONE, TWO, THREE ).map(Option::name)
		}
	}
}
```

And this test:
```kotlin
package com.willowtreeapps.assertk.bug

import assertk.assertThat
import assertk.assertions.containsExactly
import org.junit.Test

class OptionTest {

	@Test
	fun testCompatibility() {
		val expectedValues = arrayOf( "ONE", "TWO" )
		assertThat(Option.getCompatibleOptions()).containsExactly(*expectedValues)
	}
}

```

IntelliJ's test output is:
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java -ea -Didea.test.cyclic.buffer.size=4194304 "-javaagent:/Users/geoffrey/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/191.6707.61/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=61653:/Users/geoffrey/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/191.6707.61/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Users/geoffrey/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/191.6707.61/IntelliJ IDEA.app/Contents/lib/idea_rt.jar:/Users/geoffrey/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/191.6707.61/IntelliJ IDEA.app/Contents/plugins/junit/lib/junit-rt.jar:/Users/geoffrey/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/191.6707.61/IntelliJ IDEA.app/Contents/plugins/junit/lib/junit5-rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/tools.jar:/Users/geoffrey/dev/work/opensource/assertk-bug/target/test-classes:/Users/geoffrey/dev/work/opensource/assertk-bug/target/classes:/Users/geoffrey/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.30/kotlin-stdlib-jdk8-1.3.30.jar:/Users/geoffrey/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.3.30/kotlin-stdlib-1.3.30.jar:/Users/geoffrey/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.30/kotlin-stdlib-common-1.3.30.jar:/Users/geoffrey/.m2/repository/org/jetbrains/annotations/13.0/annotations-13.0.jar:/Users/geoffrey/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.3.30/kotlin-stdlib-jdk7-1.3.30.jar:/Users/geoffrey/.m2/repository/org/jetbrains/kotlin/kotlin-reflect/1.3.30/kotlin-reflect-1.3.30.jar:/Users/geoffrey/.m2/repository/com/willowtreeapps/assertk/assertk-jvm/0.13/assertk-jvm-0.13.jar:/Users/geoffrey/.m2/repository/com/willowtreeapps/assertk/assertk-common/0.13/assertk-common-0.13.jar:/Users/geoffrey/.m2/repository/com/willowtreeapps/opentest4k/opentest4k-common/1.1.0/opentest4k-common-1.1.0.jar:/Users/geoffrey/.m2/repository/com/willowtreeapps/opentest4k/opentest4k-jvm/1.1.0/opentest4k-jvm-1.1.0.jar:/Users/geoffrey/.m2/repository/org/opentest4j/opentest4j/1.1.0/opentest4j-1.1.0.jar:/Users/geoffrey/.m2/repository/junit/junit/4.12/junit-4.12.jar:/Users/geoffrey/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 -junit4 com.willowtreeapps.assertk.bug.OptionTest
objc[92182]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java (0x10d1eb4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10d2774e0). One of the two will be used. Which one is undefined.

org.opentest4j.AssertionFailedError: expected to contain exactly:
 at index:2 un
Expected :null
Actual   :null
<Click to see difference>


	at com.willowtreeapps.assertk.bug.OptionTest.testCompatibility(OptionTest.kt:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255
```

The Maven output is better:
```
-------------------------------------------------------------------------------
Test set: com.willowtreeapps.assertk.bug.OptionTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.161 sec <<< FAILURE!
testCompatibility(com.willowtreeapps.assertk.bug.OptionTest)  Time elapsed: 0.08 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected to contain exactly:
 at index:2 unexpected:<"THREE">
        at com.willowtreeapps.assertk.bug.OptionTest.testCompatibility(OptionTest.kt:12)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by geoffreywiseman** [comment]
I put all of the above in a tiny project, if it's easier for you, I could turn it into a GitHub repo.

**Comment by evant** [comment]
oh, that's interesting, why would the intellij output be different?

**Comment by evant** [comment]
I think I might have enough info to go on, but if you want to make a test project that would be appreciated.

**Comment by geoffreywiseman** [comment]
https://github.com/geoffreywiseman/assertk-bug

**Comment by geoffreywiseman** [comment]
Despite the repo name, the problem may well be an IntelliJ issue, or a combination of IntelliJ / Assertk, but I figured I'd start with you guys and go from there.

**Comment by evant** [comment]
Alright, figured it out. Seems like assertk is incorrectly passing in null for expected and actual values to `AssertionFailedError` when they shouldn't be defined. This is triggering intellij's comparison display. It does seem weird though that intellij doesn't show the entire message when doing this though.
